# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-30 17:37
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxiservice', '0002_auto_20160630_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(code='invalid_phone_number', message='Phone number is not valid', regex='^[+-()0-9]*$')]),
        ),
    ]
